export const GROUP = {
  SYMBOL: "symbol",
  HELPER: "helper",
  TEST: "test",
  RESULT: "result",
  SUGGESTION: "suggestion",
  NEW: "new",
};

const symbolOptions = [
  { value: " ", label: "、", group: GROUP.SYMBOL },
  { value: ",", label: "，", group: GROUP.SYMBOL },
  { value: ".", label: "。", group: GROUP.SYMBOL },
];

const helperOptions = [
  { value: "T", label: "檢查", group: GROUP.HELPER },
  { value: "ENDING", label: "，享悅診所關心您。", group: GROUP.HELPER },
];

const testOptions = [
  { value: "AC", label: "飯前血糖", group: GROUP.TEST },
  { value: "AFP", label: "肝癌指數AFP", group: GROUP.TEST },
  { value: "ALB", label: "白蛋白", group: GROUP.TEST },
  { value: "AM", label: "阿米巴痢疾試驗", group: GROUP.TEST },
  { value: "AML", label: "澱粉酶", group: GROUP.TEST },
  { value: "AMP", label: "安非他命試驗", group: GROUP.TEST },
  { value: "AN", label: "貧血", group: GROUP.TEST },
  { value: "ANA", label: "抗核抗體", group: GROUP.TEST },
  { value: "BAC", label: "細菌指數", group: GROUP.TEST },
  { value: "BASO", label: "鹼性白血球佔比", group: GROUP.TEST },
  { value: "BD", label: "骨質密度超音波檢定T值", group: GROUP.TEST },
  { value: "BDT", label: "桿菌性痢疾試驗", group: GROUP.TEST },
  { value: "BT", label: "血型", group: GROUP.TEST },
  { value: "BUN", label: "尿素氮", group: GROUP.TEST },
  { value: " CA", label: "鈣", group: GROUP.TEST },
  { value: "CEA", label: "直腸及胃腫瘤", group: GROUP.TEST },
  { value: "CHO", label: "總膽固醇", group: GROUP.TEST },
  { value: "CHR", label: "霍亂弧菌檢查", group: GROUP.TEST },
  { value: "CKD", label: "慢性腎臟病", group: GROUP.TEST },
  { value: "CI", label: "氯", group: GROUP.TEST },
  { value: "CRE", label: "肌酸酐", group: GROUP.TEST },
  { value: "CRY", label: "結晶體", group: GROUP.TEST },
  { value: "CPPD", label: "集磷酸鈣結晶", group: GROUP.TEST },
  { value: "E2", label: "女性賀爾蒙", group: GROUP.TEST },
  { value: "EM", label: "視網上皮膜", group: GROUP.TEST },
  { value: "EGFR", label: "腎絲球過濾率", group: GROUP.TEST },
  { value: "EOS", label: "嗜酸性白血球佔率", group: GROUP.TEST },
  { value: "FAT", label: "油脂", group: GROUP.TEST },
  { value: "FOBT", label: "糞便潛血試驗", group: GROUP.TEST },
  { value: "FP", label: "眼底攝影檢查結果為", group: GROUP.TEST },
  { value: "GLO", label: "葡萄糖", group: GROUP.TEST },
  { value: "GLU", label: "球蛋白", group: GROUP.TEST },
  { value: "GOT", label: "肝炎指數GOT", group: GROUP.TEST },
  { value: "GPT", label: "肝炎指數GPT", group: GROUP.TEST },
  { value: "HAG", label: "A型肝炎慢性期抗體IgG", group: GROUP.TEST },
  { value: "HAM", label: "A型肝炎集性期抗體IgG", group: GROUP.TEST },
  { value: "HB", label: "血色素", group: GROUP.TEST },
  { value: "HBAIC", label: "醣化血色素", group: GROUP.TEST },
  { value: "HBEAG", label: "B型肝炎e抗原", group: GROUP.TEST },
  { value: "HBSAB", label: "B型肝炎表面抗體", group: GROUP.TEST },
  { value: "HBSAG", label: "B型肝炎表面抗原", group: GROUP.TEST },
  { value: "HCT", label: "血容比", group: GROUP.TEST },
  { value: "HCVAB", label: "C型肝炎抗體", group: GROUP.TEST },
  { value: "HDL", label: "高密度膽固醇脂蛋白", group: GROUP.TEST },
  { value: "HEM", label: "血尿", group: GROUP.TEST },
  { value: "INR", label: "凝血酶原標準化比值", group: GROUP.TEST },
  { value: "JC", label: "關節液培養", group: GROUP.TEST },
  { value: "JR", label: "關節液常規檢查", group: GROUP.TEST },
  { value: "K", label: "鉀離子", group: GROUP.TEST },
  { value: "LDL", label: "低密度膽固醇脂蛋白", group: GROUP.TEST },
  { value: "LS", label: "雷射治療後", group: GROUP.TEST },
  { value: "LYM", label: "淋巴球佔比", group: GROUP.TEST },
  { value: "MCH", label: "平均紅血球血紅素量", group: GROUP.TEST },
  { value: "MCHC", label: "平均紅血球血紅素濃度", group: GROUP.TEST },
  { value: "MCV", label: "平均紅血球體積", group: GROUP.TEST },
  { value: "MG", label: "麻疹病毒抗體IgG", group: GROUP.TEST },
  { value: "MIG", label: "麻疹免疫蛋白", group: GROUP.TEST },
  { value: "MON", label: "單核球佔比", group: GROUP.TEST },
  { value: "MOR", label: "嗎啡試驗", group: GROUP.TEST },
  { value: "NA", label: "鈉離子", group: GROUP.TEST },
  { value: "NEU", label: "中性球佔比", group: GROUP.TEST },
  { value: "NUC", label: "有核球佔比", group: GROUP.TEST },
  { value: "OD", label: "右眼", group: GROUP.TEST },
  { value: "OS", label: "左眼", group: GROUP.TEST },
  { value: "OU", label: "雙眼", group: GROUP.TEST },
  { value: "PE", label: "義眼", group: GROUP.TEST },
  { value: "OGTT", label: "糖水試驗", group: GROUP.TEST },
  { value: "OO", label: "高密度", group: GROUP.TEST },
  { value: "P", label: "磷", group: GROUP.TEST },
  { value: "P4", label: "黃體素", group: GROUP.TEST },
  { value: "PC", label: "飯後血糖", group: GROUP.TEST },
  { value: "PH", label: "酸鹼值", group: GROUP.TEST },
  { value: "PLT", label: "血小板", group: GROUP.TEST },
  { value: "PRO", label: "蛋白質", group: GROUP.TEST },
  { value: "PRT", label: "懷孕試驗", group: GROUP.TEST },
  { value: "PSA", label: "攝護腺腫瘤", group: GROUP.TEST },
  { value: "PT", label: "凝血時間", group: GROUP.TEST },
  { value: "RA", label: "類風濕性關節炎因子", group: GROUP.TEST },
  { value: "RBC", label: "紅血球數", group: GROUP.TEST },
  { value: "RGT", label: "麩氨基轉移酶", group: GROUP.TEST },
  { value: "RM", label: "尿黏液", group: GROUP.TEST },
  { value: "RPR", label: "梅毒試驗", group: GROUP.TEST },
  { value: "SOB", label: "糞便潛血反應", group: GROUP.TEST },
  { value: "SPT", label: "糞便寄生蟲檢查", group: GROUP.TEST },
  { value: "SR", label: "糞便潛常規檢查", group: GROUP.TEST },
  { value: "SRFAT", label: "糞便檢查油脂", group: GROUP.TEST },
  { value: "ST", label: "糞便檢查", group: GROUP.TEST },
  { value: "STF", label: "糞便傷寒檢查", group: GROUP.TEST },
  { value: "SYNC", label: "滑膜細胞", group: GROUP.TEST },
  { value: "T4", label: "甲狀腺素", group: GROUP.TEST },
  { value: "TB", label: "總膽紅素", group: GROUP.TEST },
  { value: "TEST", label: "睪固酮", group: GROUP.TEST },
  { value: "TG", label: "三酸甘油脂", group: GROUP.TEST },
  { value: "TSH", label: "甲狀腺激素", group: GROUP.TEST },
  { value: "UA", label: "尿酸", group: GROUP.TEST },
  { value: "UB", label: "膽紅素", group: GROUP.TEST },
  { value: "UACR", label: "尿液微白蛋白與肌酸酐比值", group: GROUP.TEST },
  { value: "UCR", label: "尿肌酸酐", group: GROUP.TEST },
  { value: "UMA", label: "尿微量白蛋白", group: GROUP.TEST },
  { value: "U/A", label: "尿蛋白", group: GROUP.TEST },
  { value: "U/B", label: "尿細菌指數", group: GROUP.TEST },
  { value: "U/BI", label: "尿膽紅素", group: GROUP.TEST },
  { value: "U/C", label: "尿圓柱體", group: GROUP.TEST },
  { value: "U/E", label: "尿上皮細胞檢出數", group: GROUP.TEST },
  { value: "U/G", label: "尿糖指數", group: GROUP.TEST },
  { value: "U/H", label: "尿透明圓柱體檢出數", group: GROUP.TEST },
  { value: "U/K", label: "尿酮體指數", group: GROUP.TEST },
  { value: "U/L", label: "白血球解脂酶", group: GROUP.TEST },
  { value: "U/N", label: "尿亞硝酸鹽", group: GROUP.TEST },
  { value: "U/M", label: "尿黏液", group: GROUP.TEST },
  { value: "U/M/C", label: "微量白蛋白腎衰竭指數", group: GROUP.TEST },
  { value: "U/O", label: "尿草酸鈣結晶", group: GROUP.TEST },
  { value: "U/P", label: "尿蛋白", group: GROUP.TEST },
  { value: "U/P/C", label: "初期慢性腎臟病檢驗指數", group: GROUP.TEST },
  { value: "U/Q", label: "尿鱗狀上皮細胞檢出數", group: GROUP.TEST },
  { value: "U/R", label: "尿液常規檢查", group: GROUP.TEST },
  { value: "U/S", label: "尿糖指數", group: GROUP.TEST },
  { value: "U/T", label: "磷酸鹽結晶", group: GROUP.TEST },
  { value: "U/U", label: "尿酸結晶", group: GROUP.TEST },
  { value: "U/Y", label: "尿酵母菌", group: GROUP.TEST },
  { value: "OB", label: "潛血反應", group: GROUP.TEST },
  { value: "WBC", label: "白血球檢出數", group: GROUP.TEST },
  { value: "WT", label: "傷寒", group: GROUP.TEST },
  { value: "CBC", label: "常規血液檢查", group: GROUP.TEST },
];

const resultOptions = [
  { value: "R/+", label: "一價", group: GROUP.RESULT },
  { value: "R/+-", label: "微量", group: GROUP.RESULT },
  { value: "R/-+", label: "微量", group: GROUP.RESULT },
  { value: "R/++", label: "二價", group: GROUP.RESULT },
  { value: "R/+++", label: "三價", group: GROUP.RESULT },
  { value: "R/++++", label: "四價", group: GROUP.RESULT },
  { value: "R/NP", label: "無異常", group: GROUP.RESULT },
  { value: "R/OK", label: "尚可", group: GROUP.RESULT },
  { value: "R/OH", label: "過高", group: GROUP.RESULT },
  { value: "R/OL", label: "過低", group: GROUP.RESULT },
  { value: "R/MH", label: "較高", group: GROUP.RESULT },
  { value: "R/ML", label: "較低", group: GROUP.RESULT },
  { value: "R/SH", label: "稍高", group: GROUP.RESULT },
  { value: "R/SL", label: "稍低", group: GROUP.RESULT },
  { value: "R/P", label: "結果為陽性", group: GROUP.RESULT },
  { value: "R/N", label: "結果為陰性", group: GROUP.RESULT },
  { value: "R/NG", label: "無菌株生長", group: GROUP.RESULT },
  { value: "R/RD", label: "達糖尿病控制目標", group: GROUP.RESULT },
  { value: "R/BNP", label: "等皆無異常", group: GROUP.RESULT },
  { value: "R/BOH", label: "等皆過高", group: GROUP.RESULT },
  { value: "R/BOL", label: "等皆過低", group: GROUP.RESULT },
  { value: "R/BMH", label: "等皆較高", group: GROUP.RESULT },
  { value: "R/BML", label: "等皆較低", group: GROUP.RESULT },
  { value: "R/BSH", label: "等皆稍高", group: GROUP.RESULT },
  { value: "R/BSL", label: "等皆稍低", group: GROUP.RESULT },
  { value: "R/BP", label: "等皆陽性", group: GROUP.RESULT },
  { value: "R/BN", label: "等皆陰性", group: GROUP.RESULT },
  { value: "R/BRD", label: "皆達糖尿病控制目標", group: GROUP.RESULT },
  { value: "R/EDM", label: "為初期糖尿病狀態", group: GROUP.RESULT },
  { value: "R/DM", label: "達糖尿病診斷標準", group: GROUP.RESULT },
  { value: "R/LG", label: "為低血糖狀態", group: GROUP.RESULT },
  { value: "R/HG", label: "為高血糖狀態", group: GROUP.RESULT },
  { value: "R/CAT", label: "白內障", group: GROUP.RESULT },
  { value: "R/GLA", label: "疑似青光眼", group: GROUP.RESULT },
  { value: "R/FCR", label: "局部脈絡網膜炎", group: GROUP.RESULT },
  { value: "R/CHOD", label: "脈絡膜退化", group: GROUP.RESULT },
  { value: "R/CHOR", label: "脈絡及視網膜病變", group: GROUP.RESULT },
  { value: "R/PR", label: "增殖性視網膜病變", group: GROUP.RESULT },
  { value: "R/NPR", label: "非增殖性視網膜病變", group: GROUP.RESULT },
  { value: "R/DR", label: "視網膜退化性結節", group: GROUP.RESULT },
  { value: "R/RVO", label: "視網膜靜脈阻塞", group: GROUP.RESULT },
  { value: "R/RVT", label: "視網膜靜脈阻塞扭曲", group: GROUP.RESULT },
  { value: "R/RAA", label: "視網膜動脈硬化", group: GROUP.RESULT },
  { value: "R/RETM", label: "視網膜近視性病變", group: GROUP.RESULT },
  { value: "R/RP", label: "視網膜色素變性", group: GROUP.RESULT },
  { value: "R/OA", label: "視神經排萎縮", group: GROUP.RESULT },
  { value: "R/MACE", label: "黃斑部水腫", group: GROUP.RESULT },
  { value: "R/MACM", label: "黃斑部近視性病變", group: GROUP.RESULT },
  { value: "R/MACO", label: "黃斑部病變", group: GROUP.RESULT },
  { value: "R/MACP", label: "黃斑部生膜", group: GROUP.RESULT },
  { value: "R/SMD", label: "老人性黃斑病變", group: GROUP.RESULT },
  { value: "R/SNEMD", label: "老年性非滲出性黃斑退化", group: GROUP.RESULT },
  { value: "R/VO", label: "玻璃體混濁", group: GROUP.RESULT },
  { value: "R/HAV", label: "陳舊性A型肝炎感染者", group: GROUP.RESULT },
  { value: "R/HBC", label: "顯示B型肝炎病毒帶原者", group: GROUP.RESULT },
  {
    value: "R/HBR",
    label: "顯示具有B型肝炎病毒抵抗力，處於安全狀態",
    group: GROUP.RESULT,
  },
  { value: "R/HCC", label: "顯示C型肝病毒帶原者", group: GROUP.RESULT },
  { value: "R/NV", label: "無影像", group: GROUP.RESULT },
  { value: "R/BV", label: "影像不清", group: GROUP.RESULT },
  { value: "R/SO", label: "輕度疏鬆", group: GROUP.RESULT },
  { value: "R/MO", label: "中度疏鬆", group: GROUP.RESULT },
  { value: "R/MACA", label: "顯示巨球型貧血", group: GROUP.RESULT },
  {
    value: "R/MGR",
    label: "顯示具有麻疹並塗感染，需1-4週內再次追蹤",
    group: GROUP.RESULT,
  },
  { value: "R/SUTI", label: "顯示輕度尿路感染", group: GROUP.RESULT },
  { value: "R/UTI", label: "顯示明顯尿路感染", group: GROUP.RESULT },
];

const suggestionOptions = [
  { value: "S/F", label: "需門診追蹤", group: GROUP.SUGGESTION },
  { value: "S/FU", label: "需門診追蹤檢查", group: GROUP.SUGGESTION },
  { value: "S/FU6", label: "六個月後追蹤檢查", group: GROUP.SUGGESTION },
  { value: "S/FT", label: "需門診追蹤治療", group: GROUP.SUGGESTION },
  { value: "S/FUT", label: "需門診追蹤或治療", group: GROUP.SUGGESTION },
  { value: "S/FUTR", label: "需定期門診追蹤及治療", group: GROUP.SUGGESTION },
  { value: "S/FDR", label: "若有視力障礙需門診追蹤", group: GROUP.SUGGESTION },
  { value: "S/R", label: "轉診", group: GROUP.SUGGESTION },
  { value: "S/RS", label: "需轉介專科門診追蹤及治療", group: GROUP.SUGGESTION },
  { value: "S/RF", label: "需轉介專科門診處置", group: GROUP.SUGGESTION },
  { value: "S/RO", label: "需轉介眼科專科門診複查", group: GROUP.SUGGESTION },
  { value: "S/ROF", label: "需轉介眼科專科門診處置", group: GROUP.SUGGESTION },
  { value: "S/RH", label: "並轉介至醫院進行複檢", group: GROUP.SUGGESTION },
  { value: "S/CCG", label: "請繼續控制糖分攝取", group: GROUP.SUGGESTION },
  { value: "S/CCL", label: "請繼續控制油脂攝取", group: GROUP.SUGGESTION },
  {
    value: "S/CCGL",
    label: "請繼續控制糖分及油脂攝取",
    group: GROUP.SUGGESTION,
  },
  { value: "S/ICG", label: "請加強控制糖分攝取", group: GROUP.SUGGESTION },
  { value: "S/ICL", label: "請加強控制油脂攝取量", group: GROUP.SUGGESTION },
  {
    value: "S/ICGL",
    label: "請加強控制糖分及油脂攝取",
    group: GROUP.SUGGESTION,
  },
  { value: "S/BCG", label: "請按日均衡控制糖分攝取", group: GROUP.SUGGESTION },
  {
    value: "S/LG",
    label: "需適時補充糖分及門診追蹤管理",
    group: GROUP.SUGGESTION,
  },
  {
    value: "S/HG",
    label: "需注意控制糖分攝取，並每年持續追蹤",
    group: GROUP.SUGGESTION,
  },
  { value: "S/CA", label: "請增加攝取鈣質食品", group: GROUP.SUGGESTION },
  {
    value: "S/CAH",
    label: "需注意人工奶油及氫化油脂攝取量",
    group: GROUP.SUGGESTION,
  },
  {
    value: "S/CHT",
    label: "需注意控制高熱量食物及反式脂肪的攝取量",
    group: GROUP.SUGGESTION,
  },
  {
    value: "S/HBV",
    label: "建議注射B型肝炎疫苗，預防病毒肝炎",
    group: GROUP.SUGGESTION,
  },
  {
    value: "S/SUTI",
    label: "需多飲水多解尿勿憋尿，如有解尿不適需門診追蹤或治療",
    group: GROUP.SUGGESTION,
  },
  { value: "S/SV", label: "建議注射相關疫苗", group: GROUP.SUGGESTION },
];

export const groupedOptions = [
  {
    label: "標號",
    options: symbolOptions,
  },
  {
    label: "語助詞",
    options: helperOptions,
  },
  {
    label: "檢驗",
    options: testOptions,
  },
  {
    label: "檢驗結果",
    options: resultOptions,
  },
  {
    label: "建議",
    options: suggestionOptions,
  },
];
